export const items = {
    // Item Types
    Error: 0,
    Text: 1,
    StartBold: 2,
    EndBold: 3,
    StartItalic: 4,
    EndItalic: 5,
    Code: 6,
    EOF: 7,
    Newline: 8,
    Linebreak: 9,
    CodeBlock: 10,
    H1: 11,
    H2: 12,
    H3: 13,
    OrderedListItem: 14,
    UnorderedListItem: 15,
    Link: 16,
    Img: 17,
}
